version: "3"

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDblXWBbCdACVlwNjqor+Z+psL4GMzcA1BKC8Jd6P6uxKMpueTqDhWO++W/BNHj4puQHuWWbdjB15YoQsskFelcrrdHSPMu2rU/orA8IuaSrqpanJayulWz2JMdAc6xNtFbP2MGi0lXTKT6bVjrzGflMRWeeMcfQ0zn+8HXH8B3UmyzkPEetdzdILDIKn6Spko1PUi1s9EQA7kYhIGhdVwNV9+BaQQGvGDTShif64Q0U6/hAsHPO7uPhP6J1XxUQqRzYOk/VLZqAljaq5VvqbkvYqT3HyWF6HYT4OpOlChnyb7+DFebFORbBN94OYUIRJXPz9MmVoEGRJqAaMoDCZwiCcmTO999H6mmDfvSPkW0ihQNYp+SDnomFOmo0evgOEyCHGSt2J0NHW78ZeVP3Vb/xLD6/LE86gO/kysmhDZRJIIGRpqFbVZ/Q3ppLn91RKXTRh24wIqdLBhM4N4Q3mWWwGO2YkKB+JlGoH7FeyuGr1axiQj3n6vkYPGC2FTIEKp90AhNgTwzoTm+9sGfjiirSWfR2V8k3XVr549Zr+AjP4G+BlGbzSx7f6wtbHuhRCWaZFr749IZk8mf65pDEXiZUNuav+TD5swcgH1HpWbJx2zFniZJ86Tf3ClL/vmXVXeJ5c+QUir6XupbxDwj9oaseJ5IBWUU0zO4brUfxrlx8w== jack.lafond@icloud.com

  redis:
    image: redis
    restart: always
    volumes:
      - "redis_data:/redis/data"
    environment:
      PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDblXWBbCdACVlwNjqor+Z+psL4GMzcA1BKC8Jd6P6uxKMpueTqDhWO++W/BNHj4puQHuWWbdjB15YoQsskFelcrrdHSPMu2rU/orA8IuaSrqpanJayulWz2JMdAc6xNtFbP2MGi0lXTKT6bVjrzGflMRWeeMcfQ0zn+8HXH8B3UmyzkPEetdzdILDIKn6Spko1PUi1s9EQA7kYhIGhdVwNV9+BaQQGvGDTShif64Q0U6/hAsHPO7uPhP6J1XxUQqRzYOk/VLZqAljaq5VvqbkvYqT3HyWF6HYT4OpOlChnyb7+DFebFORbBN94OYUIRJXPz9MmVoEGRJqAaMoDCZwiCcmTO999H6mmDfvSPkW0ihQNYp+SDnomFOmo0evgOEyCHGSt2J0NHW78ZeVP3Vb/xLD6/LE86gO/kysmhDZRJIIGRpqFbVZ/Q3ppLn91RKXTRh24wIqdLBhM4N4Q3mWWwGO2YkKB+JlGoH7FeyuGr1axiQj3n6vkYPGC2FTIEKp90AhNgTwzoTm+9sGfjiirSWfR2V8k3XVr549Zr+AjP4G+BlGbzSx7f6wtbHuhRCWaZFr749IZk8mf65pDEXiZUNuav+TD5swcgH1HpWbJx2zFniZJ86Tf3ClL/vmXVXeJ5c+QUir6XupbxDwj9oaseJ5IBWUU0zO4brUfxrlx8w== jack.lafond@icloud.com

  app:
    depends_on:
      - redis
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.prod
    environment:
      REDIS_URL: redis://redis
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    command: yarn prod

volumes:
  redis_data:
  postgres_data:
